---

- name: Install system package
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - git

- name: Copy .vimrc
  template:
    src: vimrc
    dest: "{{ lookup('env','HOME') }}/.vimrc"
