---

- name: Install system package
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - git

- name: Copy .vimrc
  template:
    src: vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: Create bundle directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/bundle"
    state: directory

- name: Install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Vundle.vim"
